import { User } from '@/app/models';
import AvatarImg from '@/styles/img.png';

const mockUsers: User[] = [
  {
    id: 1,
    name: 'Bernard Acosta',
    email: 'bernardacosta@gmail.com',
    age: 23,
    avatar: AvatarImg,
  },
  {
    id: 2,
    name: 'Justin Torres',
    email: 'justintorres@gmail.com',
    age: 29,
    avatar: AvatarImg,
  },
  {
    id: 3,
    name: 'Christopher Kennedy',
    email: 'christopherkennedy@gmail.com',
    age: 37,
    avatar: AvatarImg,
  },
  {
    id: 4,
    name: 'Anne Mcdonald',
    email: 'annemcdonald@gmail.com',
    age: 41,
    avatar: AvatarImg,
  },
  {
    id: 5,
    name: 'Jennifer Murray',
    email: 'jennifermurray@gmail.com',
    age: 45,
    avatar: AvatarImg,
  },
  {
    id: 6,
    name: 'Tammy Frazier',
    email: 'tammyfrazier@gmail.com',
    age: 38,
    avatar: AvatarImg,
  },
  {
    id: 7,
    name: 'Rachel Lee',
    email: 'rachellee@gmail.com',
    age: 64,
    avatar: AvatarImg,
  },
  {
    id: 8,
    name: 'Andrea Shields',
    email: 'andreashields@gmail.com',
    age: 37,
    avatar: AvatarImg,
  },
  {
    id: 9,
    name: 'Francisco Powell',
    email: 'franciscopowell@gmail.com',
    age: 30,
    avatar: AvatarImg,
  },
  {
    id: 10,
    name: 'Russell Kemp',
    email: 'russellkemp@gmail.com',
    age: 54,
    avatar: AvatarImg,
  },
  {
    id: 11,
    name: 'Noah Moreno',
    email: 'noahmoreno@gmail.com',
    age: 20,
    avatar: AvatarImg,
  },
  {
    id: 12,
    name: 'Elizabeth Cordova',
    email: 'elizabethcordova@gmail.com',
    age: 27,
    avatar: AvatarImg,
  },
  {
    id: 13,
    name: 'Michael Murray',
    email: 'michaelmurray@gmail.com',
    age: 21,
    avatar: AvatarImg,
  },
  {
    id: 14,
    name: 'Shawn Miller',
    email: 'shawnmiller@gmail.com',
    age: 41,
    avatar: AvatarImg,
  },
  {
    id: 15,
    name: 'Tyler Hernandez',
    email: 'tylerhernandez@gmail.com',
    age: 39,
    avatar: AvatarImg,
  },
  {
    id: 16,
    name: 'Karen Decker',
    email: 'karendecker@gmail.com',
    age: 31,
    avatar: AvatarImg,
  },
  {
    id: 17,
    name: 'Susan Holmes',
    email: 'susanholmes@gmail.com',
    age: 45,
    avatar: AvatarImg,
  },
  {
    id: 18,
    name: 'Jodi Schmidt',
    email: 'jodischmidt@gmail.com',
    age: 41,
    avatar: AvatarImg,
  },
  {
    id: 19,
    name: 'Nicholas Boyer',
    email: 'nicholasboyer@gmail.com',
    age: 45,
    avatar: AvatarImg,
  },
  {
    id: 20,
    name: 'Tyler Nolan',
    email: 'tylernolan@gmail.com',
    age: 40,
    avatar: AvatarImg,
  },
  {
    id: 21,
    name: 'Kathy Clark',
    email: 'kathyclark@gmail.com',
    age: 21,
    avatar: AvatarImg,
  },
  {
    id: 22,
    name: 'Mario Fritz',
    email: 'mariofritz@gmail.com',
    age: 32,
    avatar: AvatarImg,
  },
  {
    id: 23,
    name: 'Timothy Alvarado',
    email: 'timothyalvarado@gmail.com',
    age: 53,
    avatar: AvatarImg,
  },
  {
    id: 24,
    name: 'Pamela Gordon',
    email: 'pamelagordon@gmail.com',
    age: 54,
    avatar: AvatarImg,
  },
  {
    id: 25,
    name: 'Chad Trevino',
    email: 'chadtrevino@gmail.com',
    age: 58,
    avatar: AvatarImg,
  },
  {
    id: 26,
    name: 'John Solis',
    email: 'johndysolis@gmail.com',
    age: 21,
    avatar: AvatarImg,
  },
  {
    id: 27,
    name: 'Mrs. Ruth Molina',
    email: 'mrs.ruthmolina@gmail.com',
    age: 27,
    avatar: AvatarImg,
  },
  {
    id: 28,
    name: 'Joshua Anderson',
    email: 'joshuaanderson@gmail.com',
    age: 59,
    avatar: AvatarImg,
  },
  {
    id: 29,
    name: 'Sean Farmer',
    email: 'seanfarmer@gmail.com',
    age: 43,
    avatar: AvatarImg,
  },
  {
    id: 30,
    name: 'Michael Morris',
    email: 'michaelmorris@gmail.com',
    age: 65,
    avatar: AvatarImg,
  },
];
export default mockUsers;
